# LAB 5

##### 1. Search about categorical values and preprocessing steps required to make them compatible with Sklearn.

In [41]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'Color': ['Red', 'Blue', 'Green', 'Red', 'Green', 'Blue'],
    'Fruit': ['Apple', 'Banana', 'Apple', 'Orange', 'Banana', 'Orange'],
    'Price': [1.2, 0.8, 1.3, 1.0, 0.9, 1.1]
})

df

   Color   Fruit  Price
0    Red   Apple    1.2
1   Blue  Banana    0.8
2  Green   Apple    1.3
3    Red  Orange    1.0
4  Green  Banana    0.9
5   Blue  Orange    1.1

##### 2. Convert the 'Fruit' column into numerical values using label encoding.
Use sklearn's LabelEncoder or pandas .map().

In [15]:
# i'll try to do both methods, after reading up on both - it's clear to me that the sklearn method automatically figures out the unique values in the column
# and constructs the mapping via .fit() and then transform() to replace the column data with the mapped values. 
# while the pandas method using .map() requires that we define the object that will serve as the mapping between unique column values and the numerical values and then applies the "transformation"

# from sklearn.preprocessing import LabelEncoder 

# label_encoder = LabelEncoder() 

# df["Fruit"] = label_encoder.fit_transform(df["Fruit"])
    
# ---------------------

mapping = {"Apple": 0, "Banana": 1, "Orange": 2}

df["Fruit"] = df["Fruit"].map(mapping)

df

   Color  Fruit  Price
0    Red      0    1.2
1   Blue      1    0.8
2  Green      0    1.3
3    Red      2    1.0
4  Green      1    0.9
5   Blue      2    1.1

##### 3. Apply one-hot encoding to the 'Color' column using pandas' get_dummies.
Ensure the result includes all dummy columns.

In [23]:
color_dummies = pd.get_dummies(df["Color"], prefix="Color_")

df = pd.concat([df, color_dummies], axis=1)

df

   Color   Fruit  Price  Color__Blue  Color__Green  Color__Red
0    Red   Apple    1.2        False         False        True
1   Blue  Banana    0.8         True         False       False
2  Green   Apple    1.3        False          True       False
3    Red  Orange    1.0        False         False        True
4  Green  Banana    0.9        False          True       False
5   Blue  Orange    1.1         True         False       False

##### 4. Apply one-hot encoding to the 'Fruit' column using sklearn's OneHotEncoder.
Output the result as a DataFrame.

In [31]:
from sklearn.preprocessing import OneHotEncoder

onehot_encoder = OneHotEncoder()

encoded_values = onehot_encoder.fit_transform(df[["Fruit"]]).toarray()

columns = onehot_encoder.get_feature_names_out(["Fruit"])

encoded_df = pd.DataFrame(encoded_values, columns=columns)

encoded_df

# optional, but probably what you'de wanna do in reality:

# df = pd.concat([df, encoded_df], axis=1)

# df

   Color   Fruit  Price  Fruit_Apple  Fruit_Banana  Fruit_Orange
0    Red   Apple    1.2          1.0           0.0           0.0
1   Blue  Banana    0.8          0.0           1.0           0.0
2  Green   Apple    1.3          1.0           0.0           0.0
3    Red  Orange    1.0          0.0           0.0           1.0
4  Green  Banana    0.9          0.0           1.0           0.0
5   Blue  Orange    1.1          0.0           0.0           1.0

##### 5. Apply one-hot encoding to the 'Color' column but drop the first category to avoid multicollinearity.

In [ ]:
onehot_encoder = OneHotEncoder(drop="first")

encoded_values = onehot_encoder.fit_transform(df[["Color"]]).toarray()

columns = onehot_encoder.get_feature_names_out(["Color"])

encoded_df = pd.DataFrame(encoded_values, columns=columns)

encoded_df

   Color_Green  Color_Red
0          0.0        1.0
1          0.0        0.0
2          1.0        0.0
3          0.0        1.0
4          1.0        0.0
5          0.0        0.0

##### 6. Add an 'Education' column with values ['High School', 'Bachelors', 'Masters', 'PhD']
Then encode it using ordinal encoding in this order: High School < Bachelors < Masters < PhD

df['Education'] = ['Bachelors', 'High School', 'Masters', 'PhD', 'Masters', 'High School']

In [44]:
from sklearn.preprocessing import OrdinalEncoder

df['Education'] = ['Bachelors', 'High School', 'Masters', 'PhD', 'Masters', 'High School']

ordinal_encoder = OrdinalEncoder(categories=[['High School', 'Bachelors', 'Masters', 'PhD']])

df['Education_encoded'] = ordinal_encoder.fit_transform(df[['Education']])

df

   Color   Fruit  Price    Education  Education_encoded
0    Red   Apple    1.2    Bachelors                1.0
1   Blue  Banana    0.8  High School                0.0
2  Green   Apple    1.3      Masters                2.0
3    Red  Orange    1.0          PhD                3.0
4  Green  Banana    0.9      Masters                2.0
5   Blue  Orange    1.1  High School                0.0

##### 7. Explain in a Markdown cell below when to use one-hot encoding vs. label encoding.

the distinction is very simple, 

- label encoding encodes into numerical values by mapping the original values to a number, while this works in a lot of cases, it sometimes introduces problems: 
    for example, the algorithm might infer an semantic meaning / relationships between between encoded values, like 2 is twice of 1, or 1 is in-between 2 and 0 (ordering, heirarchy, etc),
    so the main use-case for label encoding is when we don't care about this issue or you really have logic of the relationship between encoded values written out. 

- one-hot encoduing is primarily used to solve the above issue, when we want to encode things like Colors, Fruits, Cities, etc... and have no ordering or hierarchy 
    or any semantic meaning / relationships between encoded numbers - it solves this by creating a unique column for every unique value in the column we're encoding and assigning
    1 in the row that represents the value and 0 for every other row.

# Well Done!